apiVersion: batch/v1
kind: Job
metadata:
  name: wafra-migrations
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: abobker/wafra-api:1.2
          command: ["dotnet", "Wafra.api.dll", "--migrate"]
          env:
            - name: ConnectionStrings__Default
              value: "Server=postgres;Port=5432;Database=WafraDB;User Id=postgres;Password=postgres;Include Error Detail=true"
      restartPolicy: Never
